# Generated by Django 5.2.15 on 2026-06-04 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheep', '0003_alter_sheep_eid_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_date', models.DateField(verbose_name='Datum pripusta')),
                ('expected_lambing_date', models.DateField(blank=True, null=True, verbose_name='Očekivano janjenje')),
                ('notes', models.TextField(blank=True, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ewe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breedings_as_ewe', to='sheep.sheep', verbose_name='Ovca')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breedings_as_ram', to='sheep.sheep', verbose_name='Ovan')),
            ],
        ),
    ]
