# Generated by Django 5.2.15 on 2026-06-04 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_alter_farm_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid_number', models.CharField(max_length=50, unique=True, verbose_name='Životni broj')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Naziv / nadimak')),
                ('breed', models.CharField(choices=[('CIGAJA', 'Cigaja'), ('CRESKA', 'Creska ovca'), ('DALMATINSKA_PRAMENKA', 'Dalmatinska pramenka'), ('DUBROVACKA_RUDA', 'Dubrovačka ovca – ruda'), ('ISTARSKA', 'Istarska ovca'), ('KRCKA', 'Krčka ovca'), ('LICKA_PRAMENKA', 'Lička pramenka'), ('PASKA', 'Paška ovca'), ('RAPSKA', 'Rapska ovca'), ('ISTOCNOFRIZIJSKA', 'Istočnofrizijska ovca'), ('MERINOLANDSCHAF', 'Merinolnadschaf / merinolandšaf'), ('ROMANOVSKA', 'Romanovska ovca'), ('SOLCAVSKO_JEZERSKA', 'Solčavsko-jezerska ovca'), ('SUFFOLK', 'Suffolk / safolk'), ('TRAVNICKA_PRAMENKA', 'Travnička / vlašićka / dubska pramenka'), ('DORPER', 'Dorper'), ('TEXEL', 'Texel / teksel'), ('KERRY_HILL', 'Kerry Hill'), ('CLUN_FOREST', 'Clun forest'), ('KAMERUNSKA', 'Kamerunska ovca'), ('BERRICHON_DU_CHER', 'Berrichon du Cher'), ('LACAUNE', 'Lacaune / lakon'), ('OSTALO', 'Ostalo')], default='SOLCAVSKO_JEZERSKA', max_length=50, verbose_name='Pasmina')),
                ('sex', models.CharField(choices=[('Z', 'Žensko'), ('M', 'Muško')], default='Z', max_length=1, verbose_name='Spol')),
                ('birth_date', models.DateField(verbose_name='Datum rođenja')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktivna'), ('SOLD', 'Prodana'), ('DEAD', 'Uginula')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheep', to='farms.farm')),
            ],
        ),
    ]
