# Generated by Django 5.2.15 on 2026-06-04 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheep',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sheep',
            name='status',
        ),
        migrations.AddField(
            model_name='sheep',
            name='category',
            field=models.CharField(choices=[('JANJE', 'Janje'), ('SILJEZICA', 'Šilježica'), ('OVNIC', 'Ovnić'), ('OVCA', 'Ovca'), ('OVAN', 'Ovan')], default='JANJE', max_length=20, verbose_name='Kategorija'),
        ),
        migrations.AddField(
            model_name='sheep',
            name='is_breeding_ram',
            field=models.BooleanField(default=False, verbose_name='Rasplodni ovan'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='eid_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Životni broj mora biti u formatu HR 123456789.', regex='^HR \\d{9}$')], verbose_name='Životni broj'),
        ),
    ]
