# Generated by Django 5.2.15 on 2026-06-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheep', '0002_remove_sheep_name_remove_sheep_status_sheep_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheep',
            name='eid_number',
            field=models.CharField(max_length=12, unique=True, verbose_name='Životni broj'),
        ),
    ]
