# Generated by Django 5.2.15 on 2026-06-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheep', '0003_alter_sheep_eid_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='exit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum izlaska'),
        ),
        migrations.AddField(
            model_name='sheep',
            name='exit_reason',
            field=models.TextField(blank=True, verbose_name='Razlog / napomena izlaska'),
        ),
        migrations.AddField(
            model_name='sheep',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktivno'), ('SOLD', 'Prodano'), ('DEAD', 'Uginulo'), ('SLAUGHTERED', 'Zaklano')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
    ]
