# Generated by Django 5.2.15 on 2026-06-04 15:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheep', '0003_alter_sheep_eid_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lambing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lambing_date', models.DateField(verbose_name='Datum janjenja')),
                ('father', models.CharField(blank=True, max_length=100, verbose_name='Otac / ovan')),
                ('notes', models.TextField(blank=True, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lambings', to='sheep.sheep', verbose_name='Majka')),
            ],
        ),
        migrations.CreateModel(
            name='Lamb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Markica mora biti u formatu HR 123456789.', regex='^$|^HR \\d{9}$')], verbose_name='Broj markice')),
                ('sex', models.CharField(choices=[('Z', 'Žensko'), ('M', 'Muško')], max_length=1, verbose_name='Spol')),
                ('marking_date', models.DateField(blank=True, null=True, verbose_name='Datum markiranja')),
                ('notes', models.TextField(blank=True, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lambing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lambs', to='lambing.lambing', verbose_name='Janjenje')),
            ],
        ),
    ]
