# Generated by Django 5.2.15 on 2026-06-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lambing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lamb',
            name='tag_number',
        ),
        migrations.AddField(
            model_name='lamb',
            name='initial_tag',
            field=models.CharField(default=0, max_length=3, verbose_name='Inicijalna oznaka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lamb',
            name='official_tag',
            field=models.CharField(blank=True, max_length=12, verbose_name='Službena markica'),
        ),
        migrations.AddField(
            model_name='lambing',
            name='lamb_count',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 janje'), (2, '2 janjeta'), (3, '3 janjeta'), (4, '4 janjeta'), (5, '5 janjadi')], default=1, verbose_name='Broj janjadi'),
        ),
        migrations.AlterField(
            model_name='lamb',
            name='marking_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum službenog markiranja'),
        ),
        migrations.AlterField(
            model_name='lambing',
            name='father',
            field=models.CharField(blank=True, max_length=12, verbose_name='Otac / ovan'),
        ),
    ]
