# Generated by Django 5.2.15 on 2026-06-04 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lambing', '0002_remove_lamb_tag_number_lamb_initial_tag_and_more'),
        ('sheep', '0004_sheep_exit_date_sheep_exit_reason_sheep_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamb',
            name='converted_sheep',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lamb', to='sheep.sheep', verbose_name='Povezano grlo'),
        ),
    ]
