# Generated by Django 5.2.15 on 2026-06-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lambing', '0003_lamb_converted_sheep'),
        ('sheep', '0004_sheep_exit_date_sheep_exit_reason_sheep_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamb',
            name='breed',
            field=models.CharField(blank=True, choices=[('CIGAJA', 'Cigaja'), ('CRESKA', 'Creska ovca'), ('DALMATINSKA_PRAMENKA', 'Dalmatinska pramenka'), ('DUBROVACKA_RUDA', 'Dubrovačka ovca – ruda'), ('ISTARSKA', 'Istarska ovca'), ('KRCKA', 'Krčka ovca'), ('LICKA_PRAMENKA', 'Lička pramenka'), ('PASKA', 'Paška ovca'), ('RAPSKA', 'Rapska ovca'), ('ISTOCNOFRIZIJSKA', 'Istočnofrizijska ovca'), ('MERINOLANDSCHAF', 'Merinolnadschaf / merinolandšaf'), ('ROMANOVSKA', 'Romanovska ovca'), ('SOLCAVSKO_JEZERSKA', 'Solčavsko-jezerska ovca'), ('SUFFOLK', 'Suffolk / safolk'), ('TRAVNICKA_PRAMENKA', 'Travnička / vlašićka / dubska pramenka'), ('DORPER', 'Dorper'), ('TEXEL', 'Texel / teksel'), ('KERRY_HILL', 'Kerry Hill'), ('CLUN_FOREST', 'Clun forest'), ('KAMERUNSKA', 'Kamerunska ovca'), ('BERRICHON_DU_CHER', 'Berrichon du Cher'), ('LACAUNE', 'Lacaune / lakon'), ('OSTALO', 'Ostalo')], max_length=50, verbose_name='Pasmina janjeta'),
        ),
        migrations.AddField(
            model_name='lambing',
            name='father_sheep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fathered_lambings', to='sheep.sheep', verbose_name='Otac iz stada'),
        ),
        migrations.AlterField(
            model_name='lambing',
            name='father',
            field=models.CharField(blank=True, max_length=12, verbose_name='Otac / ovan izvan stada'),
        ),
    ]
