# Generated by Django 5.2.15 on 2026-06-04 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lambing', '0003_lamb_converted_sheep'),
        ('sheep', '0004_sheep_exit_date_sheep_exit_reason_sheep_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum vaganja')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Težina kg')),
                ('notes', models.TextField(blank=True, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lamb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='lambing.lamb', verbose_name='Janje')),
                ('sheep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='sheep.sheep', verbose_name='Grlo')),
            ],
        ),
    ]
