# Generated by Django 5.2.15 on 2026-06-04 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheep', '0003_alter_sheep_eid_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeterinaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('VACCINATION', 'Cijepljenje'), ('TREATMENT', 'Liječenje'), ('DISEASE', 'Bolest'), ('OTHER', 'Ostalo')], max_length=20, verbose_name='Vrsta zapisa')),
                ('date', models.DateField(verbose_name='Datum')),
                ('title', models.CharField(max_length=150, verbose_name='Naziv')),
                ('medicine', models.CharField(blank=True, max_length=150, verbose_name='Lijek / cjepivo')),
                ('vet_name', models.CharField(blank=True, max_length=150, verbose_name='Veterinar')),
                ('withdrawal_period', models.PositiveIntegerField(blank=True, null=True, verbose_name='Karenca u danima')),
                ('notes', models.TextField(blank=True, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veterinary_records', to='sheep.sheep', verbose_name='Grlo')),
            ],
        ),
    ]
