# Generated by Django 5.2.15 on 2026-06-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaryrecord',
            name='performed_by',
            field=models.CharField(choices=[('SELF', 'Samostalno'), ('VET', 'Veterinar')], default='SELF', max_length=10, verbose_name='Tko je izvršio'),
        ),
        migrations.AlterField(
            model_name='veterinaryrecord',
            name='vet_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ime veterinara'),
        ),
    ]
